// Static lists for the free import-time email filter. No dependencies, no
// network — these are bundled with the app and matched in memory.
//
// Keep these lean and curated. The disposable set below covers the temp-mail
// services that show up in real lists; it is deliberately NOT the full 100k-row
// open-source dump (that would bloat the serverless bundle for little gain).
// To refresh occasionally, pull from:
//   https://github.com/disposable-email-domains/disposable-email-domains
// and paste in any newly-common domains you actually see bouncing.

// Local-parts that address a shared mailbox rather than a person. These bounce
// and complain at higher rates, so we flag (not drop) them for human review.
export const ROLE_PREFIXES = new Set<string>([
  "admin",
  "administrator",
  "billing",
  "compliance",
  "contact",
  "enquiries",
  "enquiry",
  "feedback",
  "help",
  "helpdesk",
  "hello",
  "hi",
  "hostmaster",
  "info",
  "inquiries",
  "inquiry",
  "mail",
  "mailer-daemon",
  "marketing",
  "newsletter",
  "no-reply",
  "noreply",
  "office",
  "postmaster",
  "sales",
  "security",
  "support",
  "team",
  "webmaster",
]);

// Common disposable / throwaway mail domains. Match is exact on the domain.
export const DISPOSABLE_DOMAINS = new Set<string>([
  "0-mail.com",
  "0clickemail.com",
  "10minutemail.com",
  "10minutemail.net",
  "20minutemail.com",
  "33mail.com",
  "guerrillamail.com",
  "guerrillamail.net",
  "guerrillamail.org",
  "guerrillamail.biz",
  "guerrillamailblock.com",
  "sharklasers.com",
  "grr.la",
  "mailinator.com",
  "mailinator.net",
  "mailinator2.com",
  "notmailinator.com",
  "reallymymail.com",
  "spamherelots.com",
  "tempmail.com",
  "temp-mail.org",
  "temp-mail.io",
  "tempmailo.com",
  "tempr.email",
  "tmpmail.org",
  "tmpmail.net",
  "throwawaymail.com",
  "throwam.com",
  "trashmail.com",
  "trashmail.de",
  "trashmail.net",
  "trash-mail.com",
  "getnada.com",
  "nada.email",
  "dispostable.com",
  "fakeinbox.com",
  "fakemailgenerator.com",
  "yopmail.com",
  "yopmail.net",
  "yopmail.fr",
  "cool.fr.nf",
  "jetable.org",
  "maildrop.cc",
  "mailnesia.com",
  "mintemail.com",
  "mohmal.com",
  "mytemp.email",
  "getairmail.com",
  "spam4.me",
  "moakt.com",
  "tempinbox.com",
  "tempmailaddress.com",
  "emailondeck.com",
  "email-temp.com",
  "burnermail.io",
  "mailcatch.com",
  "inboxbear.com",
  "inboxkitten.com",
  "harakirimail.com",
  "discard.email",
  "discardmail.com",
  "spambog.com",
  "spambox.us",
  "spamgourmet.com",
  "wegwerfemail.de",
  "einrot.com",
  "fleckmail.de",
  "tempail.com",
  "10minemail.com",
  "20email.eu",
  "mail-temp.com",
  "temporary-mail.net",
  "luxusmail.org",
  "1secmail.com",
  "1secmail.org",
  "1secmail.net",
  "kzccv.com",
  "qiott.com",
  "wuuvo.com",
  "vddaz.com",
  "36zik.email",
]);

// Likely typos of the big free providers. If someone writes @gmial.com we can
// surface the intended domain. Kept small and high-confidence on purpose.
export const TYPO_DOMAINS: Record<string, string> = {
  "gmai.com": "gmail.com",
  "gmial.com": "gmail.com",
  "gmal.com": "gmail.com",
  "gmail.co": "gmail.com",
  "gmail.cm": "gmail.com",
  "gmail.con": "gmail.com",
  "gmailcom": "gmail.com",
  "gmaill.com": "gmail.com",
  "gnail.com": "gmail.com",
  "gamil.com": "gmail.com",
  "hotmial.com": "hotmail.com",
  "hotmai.com": "hotmail.com",
  "hotmal.com": "hotmail.com",
  "hotmail.co": "hotmail.com",
  "hotmail.con": "hotmail.com",
  "hotnail.com": "hotmail.com",
  "yahooo.com": "yahoo.com",
  "yaho.com": "yahoo.com",
  "yahoo.co": "yahoo.com",
  "yahoo.con": "yahoo.com",
  "yhaoo.com": "yahoo.com",
  "outlok.com": "outlook.com",
  "outook.com": "outlook.com",
  "outlook.co": "outlook.com",
  "outlook.con": "outlook.com",
  "iclould.com": "icloud.com",
  "icloud.co": "icloud.com",
  "icloud.con": "icloud.com",
};
